// ============================================================================
// triz-data.js — Single Canonical Source of Truth for TRIZ Reference Data
// ============================================================================
//
// This ES module is the ONLY authoritative source for:
//   - 39 classical TRIZ engineering parameters
//   - 40 classical TRIZ inventive principles (with canonical descriptions)
//   - Classical TRIZ contradiction matrix
//
// Consumed by:
//   - Browser: <script type="module" src="app.js"> → import from './triz-data.js'
//   - Worker:  import from './triz-data.js' (resolved by bundler at build time)
//
// DO NOT create a second copy of this data anywhere.
// DO NOT populate matrix cells or canonical descriptions from LLM, internet,
//    or any source other than the researcher's manual entry.
// ============================================================================

// === 39 Classical TRIZ Engineering Parameters ===
// Migrated from existing repository (worker.js Set + triz.html option values).
export const TRIZ_PARAMETERS = [
  { id: 1, name: "Weight of moving object" },
  { id: 2, name: "Weight of stationary object" },
  { id: 3, name: "Length of moving object" },
  { id: 4, name: "Length of stationary object" },
  { id: 5, name: "Area of moving object" },
  { id: 6, name: "Area of stationary object" },
  { id: 7, name: "Volume of moving object" },
  { id: 8, name: "Volume of stationary object" },
  { id: 9, name: "Speed" },
  { id: 10, name: "Force" },
  { id: 11, name: "Stress or pressure" },
  { id: 12, name: "Shape" },
  { id: 13, name: "Stability of object" },
  { id: 14, name: "Strength" },
  { id: 15, name: "Duration of action of moving object" },
  { id: 16, name: "Duration of action of stationary object" },
  { id: 17, name: "Temperature" },
  { id: 18, name: "Heat transmission" },
  { id: 19, name: "Amount of substance" },
  { id: 20, name: "Strength of noise" },
  { id: 21, name: "Strength of light" },
  { id: 22, name: "Use of energy by object" },
  { id: 23, name: "Use of energy by moving object" },
  { id: 24, name: "Loss of energy" },
  { id: 25, name: "Loss of substance" },
  { id: 26, name: "Loss of information" },
  { id: 27, name: "Reliability" },
  { id: 28, name: "Accuracy of measurement" },
  { id: 29, name: "Accuracy of production" },
  { id: 30, name: "Harmful factors acting on object" },
  { id: 31, name: "Harmful factors generated by object" },
  { id: 32, name: "Ease of manufacture" },
  { id: 33, name: "Ease of operation" },
  { id: 34, name: "Ease of repair" },
  { id: 35, name: "Adaptability" },
  { id: 36, name: "Complexity of device" },
  { id: 37, name: "Complexity of control" },
  { id: 38, name: "Level of automation" },
  { id: 39, name: "Productivity" }
];

// === 40 Classical TRIZ Inventive Principles ===
// Names migrated from existing repository (worker.js Map).
// canonicalDescription: array of short, domain-neutral statements.
// DO NOT populate descriptions yourself — researcher will supply them.
export const TRIZ_PRINCIPLES = [
  {
    id: 1,
    name: "Segmentation",
    canonicalDescription: [
      "Divide an object into independent parts.",
      "Make an object easy to disassemble.",
      "Increase the degree of fragmentation or segmentation."
    ]
  },

  {
    id: 2,
    name: "Taking out",
    canonicalDescription: [
      "Separate an interfering part or property from an object, or single out the only necessary part (or property) of an object."
    ]
  },

  {
    id: 3,
    name: "Local quality",
    canonicalDescription: [
      "Change an object's structure from uniform to non-uniform, change an external environment (or external influence) from uniform to non-uniform.",
      "Make each part of an object function in conditions most suitable for its operation.",
      "Make each part of an object fulfill a different and useful function."
    ]
  },

  {
    id: 4,
    name: "Asymmetry",
    canonicalDescription: [
      "Change the shape of an object from symmetrical to asymmetrical.",
      "If an object is asymmetrical, increase its degree of asymmetry."
    ]
  },

  {
    id: 5,
    name: "Merging",
    canonicalDescription: [
      "Bring closer together (or merge) identical or similar objects, assemble identical or similar parts to perform parallel operations.",
      "Make operations contiguous or parallel; bring them together in time."
    ]
  },

  {
    id: 6,
    name: "Universality",
    canonicalDescription: [
      "Make a part or object perform multiple functions; eliminate the need for other parts."
    ]
  },

  {
    id: 7,
    name: "Nested doll",
    canonicalDescription: [
      "Place one object inside another; place each object, in turn, inside the other.",
      "Make one part pass through a cavity in the other."
    ]
  },

  {
    id: 8,
    name: "Anti-weight",
    canonicalDescription: [
      "To compensate for the weight of an object, merge it with other objects that provide lift.",
      "To compensate for the weight of an object, make it interact with the environment (e.g. use aerodynamic, hydrodynamic, buoyancy and other forces)."
    ]
  },

  {
    id: 9,
    name: "Preliminary anti-action",
    canonicalDescription: [
      "If it will be necessary to do an action with both harmful and useful effects, this action should be replaced with anti-actions to control harmful effects.",
      "Create beforehand stresses in an object that will oppose known undesirable working stresses later on."
    ]
  },

  {
    id: 10,
    name: "Preliminary action",
    canonicalDescription: [
      "Perform, before it is needed, the required change of an object (either fully or partially).",
      "Pre-arrange objects such that they can come into action from the most convenient place and without losing time for their delivery."
    ]
  },

  {
    id: 11,
    name: "Beforehand cushioning",
    canonicalDescription: [
      "Prepare emergency means beforehand to compensate for the relatively low reliability of an object."
    ]
  },

  {
    id: 12,
    name: "Equipotentiality",
    canonicalDescription: [
      "In a potential field, limit position changes (e.g. change operating conditions to eliminate the need to raise or lower objects in a gravity field)."
    ]
  },

  {
    id: 13,
    name: "The other way round",
    canonicalDescription: [
      "Invert the action(s) used to solve the problem (e.g. instead of cooling an object, heat it).",
      "Make movable parts (or the external environment) fixed, and fixed parts movable.",
      "Turn the object (or process) 'upside down'."
    ]
  },

  {
    id: 14,
    name: "Spheroidality - Curvature",
    canonicalDescription: [
      "Instead of using rectilinear parts, surfaces, or forms, use curvilinear ones; move from flat surfaces to spherical ones; from parts shaped as a cube (parallelepiped) to ball-shaped structures.",
      "Use rollers, balls, spirals, domes.",
      "Go from linear to rotary motion, use centrifugal forces."
    ]
  },

  {
    id: 15,
    name: "Dynamics",
    canonicalDescription: [
      "Allow (or design) the characteristics of an object, external environment, or process to change to be optimal or to find an optimal operating condition.",
      "Divide an object into parts capable of movement relative to each other.",
      "If an object (or process) is rigid or inflexible, make it movable or adaptive."
    ]
  },

  {
    id: 16,
    name: "Partial or excessive actions",
    canonicalDescription: [
      "If 100 percent of an object is hard to achieve using a given solution method then, by using 'slightly less' or 'slightly more' of the same method, the problem may be considerably easier to solve."
    ]
  },

  {
    id: 17,
    name: "Another dimension",
    canonicalDescription: [
      "To move an object in two- or three-dimensional space.",
      "Use a multi-story arrangement of objects instead of a single-story arrangement.",
      "Tilt or re-orient the object, lay it on its side.",
      "Use 'another side' of a given area."
    ]
  },

  {
    id: 18,
    name: "Mechanical vibration",
    canonicalDescription: [
      "Cause an object to oscillate or vibrate.",
      "Increase its frequency (even up to the ultrasonic).",
      "Use an object's resonant frequency.",
      "Use piezoelectric vibrators instead of mechanical ones.",
      "Use combined ultrasonic and electromagnetic field oscillations."
    ]
  },

  {
    id: 19,
    name: "Periodic action",
    canonicalDescription: [
      "Instead of continuous action, use periodic or pulsating actions.",
      "If an action is already periodic, change the periodic magnitude or frequency.",
      "Use pauses between impulses to perform a different action."
    ]
  },

  {
    id: 20,
    name: "Continuity of useful action",
    canonicalDescription: [
      "Carry on work continuously; make all prts of an object work at full load, all the time.",
      "Eliminate all idle or intermittent actions or work."
    ]
  },

  {
    id: 21,
    name: "Skipping",
    canonicalDescription: [
      "Conduct a process , or certain stages (e.g. destructible, harmful or hazardous operations) at high speed."
    ]
  },

  {
    id: 22,
    name: "Blessing in disguise",
    canonicalDescription: [
      "Use harmful factors (particularly, harmful effects of the environment or surroundings) to achieve a positive effect.",
      "Eliminate the primary harmful action by adding it to another harmful action to resolve the problem.",
      "Amplify a harmful factor to such a degree that it is no longer harmful."
    ]
  },

  {
    id: 23,
    name: "Feedback",
    canonicalDescription: [
      "Introduce feedback (referring back, cross-checking) to improve a process or action.",
      "If feedback is already used, change its magnitude or influence."
    ]
  },

  {
    id: 24,
    name: "Intermediary",
    canonicalDescription: [
      "Use an intermediary carrier article or intermediary process.",
      "Merge one object temporarily with another (which can be easily removed)."
    ]
  },

  {
    id: 25,
    name: "Self-service",
    canonicalDescription: [
      "Make an object serve itself by performing auxiliary helpful functions",
      "Use waste resources, energy, or substances."
    ]
  },

  {
    id: 26,
    name: "Copying",
    canonicalDescription: [
      "Instead of an unavailable, expensive, fragile object, use simpler and inexpensive copies.",
      "Replace an object, or process with optical copies.",
      "If visible optical copies are already used, move to infrared or ultraviolet copies."
    ]
  },

  {
    id: 27,
    name: "Cheap short-living objects",
    canonicalDescription: [
      "Replace an inexpensive object with a multiple of inexpensive objects, comprising certain qualities (such as service life, for instance)."
    ]
  },

  {
    id: 28,
    name: "Mechanics substitution",
    canonicalDescription: [
      "Replace a mechanical means with a sensory (optical, acoustic, taste or smell) means.",
      "Use electric, magnetic and electromagnetic fields to interact with the object.",
      "Change from static to movable fields, from unstructured fields to those having structure.",
      "Use fields in conjunction with field-activated (e.g. ferromagnetic) particles."
    ]
  },

  {
    id: 29,
    name: "Pneumatics and hydraulics",
    canonicalDescription: [
      "Use gas and liquid parts of an object instead of solid parts (e.g. inflatable, filled with liquids, air cushion, hydrostatic, hydro-reactive)."
    ]
  },

  {
    id: 30,
    name: "Flexible shells and thin films",
    canonicalDescription: [
      "Use flexible shells and thin films instead of three dimensional structures",
      "Isolate the object from the external environment using flexible shells and thin films."
    ]
  },

  {
    id: 31,
    name: "Porous materials",
    canonicalDescription: [
      "Make an object porous or add porous elements (inserts, coatings, etc.).",
      "If an object is already porous, use the pores to introduce a useful substance or function."
    ]
  },

  {
    id: 32,
    name: "Color changes",
    canonicalDescription: [
      "Change the color of an object or its external environment.",
      "Change the transparency of an object or its external environment.",
      "Use colour additives to observe hard-to-see objects or processes.",
      "If such additives are already used, employ luminescent or otherwise marked substances."
    ]
  },

  {
    id: 33,
    name: "Homogeneity",
    canonicalDescription: [
      "Make objects interacting with a given object of the same material (or material with identical properties)."
    ]
  },

  {
    id: 34,
    name: "Discarding and recovering",
    canonicalDescription: [
      "Make portions of an object that have fulfilled their functions go away (discard by dissolving, evaporating, etc.) or modify these directly during operation.",
      "Conversely, restore consumable parts of an object directly in operation."
    ]
  },

  {
    id: 35,
    name: "Parameter changes",
    canonicalDescription: [
      "Change an object's physical state (e.g. to a gas, liquid, or solid.)",
      "Change the concentration or consistency.",
      "Change the degree of flexibility.",
      "Change the temperature."
    ]
  },

  {
    id: 36,
    name: "Phase transitions",
    canonicalDescription: [
      "Use phenomena occurring during phase transitions (e.g. volume changes, loss or absorption of heat, etc.)."
    ]
  },

  {
    id: 37,
    name: "Thermal expansion",
    canonicalDescription: [
      "Use thermal expansion (or contraction) of materials.",
      "If thermal expansion is being used, use multiple materials with different coefficients of thermal expansion."
    ]
  },

  {
    id: 38,
    name: "Strong oxidants",
    canonicalDescription: [
      "Replace common air with oxygen-enriched air.",
      "Replace enriched air with pure oxygen.",
      "Expose air or oxygen to ionizing radiation.",
      "Use ionized oxygen.",
      "Replace ozonized (or ionized) oxygen with ozone."
    ]
  },

  {
    id: 39,
    name: "Inert atmosphere",
    canonicalDescription: [
      "Replace a normal environment with an inert one.",
      "Add neutral parts, or inert additives to an object."
    ]
  },

  {
    id: 40,
    name: "Composite materials",
    canonicalDescription: [
      "Change from uniform to composite (multiple) materials."
    ]
  }
];

// === Classical TRIZ Contradiction Matrix ===
// Format: "<improvingParameterId>:<worseningParameterId>": [principleId, ...]
//
// IMPORTANT: Do not populate from LLM, internet, memory, or approximation.
//            The researcher will manually enter verified matrix data.
//
// Examples (after researcher populates):
//   "12:32": [1, 5, 6],    // Shape improving, Ease of manufacture worsening → principles 1, 5, 6
//   "6:8":   [3, 6, 7],    // Area of stationary object improving, Volume of stationary object worsening
//   "15:15": [],            // Verified empty cell (no principles for this combination)
//
// A key present with value [] means "verified empty cell" (no principles apply).
// A key absent means "matrix data has not yet been entered".
export const TRIZ_MATRIX = {

  // 1. Weight of moving object
  "1:1": [0],
  "1:2": [-1],
  "1:3": [15, 8, 29, 34],
  "1:4": [-1],
  "1:5": [29, 17, 38, 34],
  "1:6": [-1],
  "1:7": [29, 2, 40, 28],
  "1:8": [-1],
  "1:9": [2, 8, 15, 38],
  "1:10": [8, 10, 18, 37],
  "1:11": [10, 36, 37, 40],
  "1:12": [10, 14, 35, 40],
  "1:13": [1, 35, 19, 39],
  "1:14": [28, 27, 18, 40],
  "1:15": [5, 34, 31, 35],
  "1:16": [-1],
  "1:17": [6, 29, 4, 38],
  "1:18": [19, 1, 32],
  "1:19": [35, 12, 34, 31],
  "1:20": [-1],
  "1:21": [12, 36, 18, 31],
  "1:22": [6, 2, 34, 19],
  "1:23": [5, 35, 3, 31],
  "1:24": [10, 24, 35],
  "1:25": [10, 35, 20, 28],
  "1:26": [3, 26, 18, 31],
  "1:27": [1, 3, 11, 27],
  "1:28": [28, 27, 35, 26],
  "1:29": [28, 35, 26, 18],
  "1:30": [22, 21, 18, 27],
  "1:31": [22, 35, 31, 39],
  "1:32": [27, 28, 1, 36],
  "1:33": [35, 3, 2, 24],
  "1:34": [2, 27, 28, 11],
  "1:35": [29, 5, 15, 8],
  "1:36": [26, 30, 36, 34],
  "1:37": [28, 29, 26, 32],
  "1:38": [26, 35, 18, 19],
  "1:39": [35, 3, 24, 37],

  // 2. Weight of stationary
  "2:1": [-1],
  "2:2": [0],
  "2:3": [-1],
  "2:4": [10, 1, 29, 35],
  "2:5": [-1],
  "2:6": [35, 30, 13, 2],
  "2:7": [-1],
  "2:8": [5, 35, 14, 2],
  "2:9": [-1],
  "2:10": [8, 10, 19, 35],
  "2:11": [13, 29, 10, 18],
  "2:12": [13, 10, 29, 14],
  "2:13": [26, 39, 1, 40],
  "2:14": [28, 2, 10, 27],
  "2:15": [-1],
  "2:16": [2, 27, 19, 6],
  "2:17": [28, 19, 32, 22],
  "2:18": [19, 32, 35],
  "2:19": [-1],
  "2:20": [18, 19, 28, 1],
  "2:21": [15, 19, 18, 22],
  "2:22": [18, 19, 28, 15],
  "2:23": [5, 8, 13, 30],
  "2:24": [10, 15, 35],
  "2:25": [10, 20, 35, 26],
  "2:26": [19, 6, 18, 26],
  "2:27": [10, 28, 8, 3],
  "2:28": [18, 26, 28],
  "2:29": [10, 1, 35, 17],
  "2:30": [2, 19, 22, 37],
  "2:31": [35, 22, 1, 39],
  "2:32": [28, 1, 9],
  "2:33": [6, 13, 1, 32],
  "2:34": [2, 27, 28, 11],
  "2:35": [19, 15, 29],
  "2:36": [1, 10, 26, 39],
  "2:37": [25, 28, 17, 15],
  "2:38": [2, 26, 35],
  "2:39": [1, 28, 15, 35],

  // 3. Length of moving object
  "3:1": [8, 15, 29, 34],
  "3:2": [-1],
  "3:3": [0],
  "3:4": [-1],
  "3:5": [15, 17, 4],
  "3:6": [-1],
  "3:7": [7, 17, 4, 35],
  "3:8": [-1],
  "3:9": [13, 4, 8],
  "3:10": [17, 10, 4],
  "3:11": [1, 8, 35],
  "3:12": [1, 8, 10, 29],
  "3:13": [1, 8, 15, 34],
  "3:14": [8, 35, 29, 34],
  "3:15": [19],
  "3:16": [-1],
  "3:17": [10, 15, 19],
  "3:18": [32],
  "3:19": [8, 35, 24],
  "3:20": [-1],
  "3:21": [1, 35],
  "3:22": [7, 2, 35, 39],
  "3:23": [4, 29, 23, 10],
  "3:24": [1, 24],
  "3:25": [15, 2, 29],
  "3:26": [29, 35],
  "3:27": [10, 14, 29, 40],
  "3:28": [28, 32, 4],
  "3:29": [10, 28, 29, 37],
  "3:30": [1, 15, 17, 24],
  "3:31": [17, 15],
  "3:32": [1, 29, 17],
  "3:33": [15, 29, 35, 4],
  "3:34": [1, 28, 10],
  "3:35": [14, 15, 1, 16],
  "3:36": [1, 19, 26, 24],
  "3:37": [35, 1, 26, 24],
  "3:38": [17, 24, 26, 16],
  "3:39": [14, 4, 28, 29],

  // 4. Length of stationary
  "4:1": [-1],
  "4:2": [35, 28, 40, 29],
  "4:3": [-1],
  "4:4": [0],
  "4:5": [-1],
  "4:6": [17, 7, 10, 40],
  "4:7": [-1],
  "4:8": [35, 8, 2, 14],
  "4:9": [-1],
  "4:10": [28, 10],
  "4:11": [1, 14, 35],
  "4:12": [13, 14, 15, 7],
  "4:13": [39, 37, 35],
  "4:14": [15, 14, 28, 26],
  "4:15": [-1],
  "4:16": [1, 10, 35],
  "4:17": [3, 35, 38, 18],
  "4:18": [3, 25],
  "4:19": [-1],
  "4:20": [-1],
  "4:21": [12, 8],
  "4:22": [6, 28],
  "4:23": [10, 28, 24, 35],
  "4:24": [24, 26],
  "4:25": [30, 29, 14],
  "4:26": [-1],
  "4:27": [15, 29, 28],
  "4:28": [32, 28, 3],
  "4:29": [2, 32, 10],
  "4:30": [1, 18],
  "4:31": [-1],
  "4:32": [15, 17, 27],
  "4:33": [2, 25],
  "4:34": [3],
  "4:35": [1, 35],
  "4:36": [1, 26],
  "4:37": [26],
  "4:38": [-1],
  "4:39": [30, 14, 7, 26],

  // 5. Area of moving object
  "5:1": [2, 17, 29, 4],
  "5:2": [-1],
  "5:3": [14, 15, 18, 4],
  "5:4": [-1],
  "5:5": [0],
  "5:6": [-1],
  "5:7": [7, 14, 17, 4],
  "5:8": [-1],
  "5:9": [29, 30, 4, 34],
  "5:10": [19, 30, 35, 2],
  "5:11": [10, 15, 36, 28],
  "5:12": [5, 34, 29, 4],
  "5:13": [11, 2, 13, 39],
  "5:14": [3, 15, 40, 14],
  "5:15": [6, 3],
  "5:16": [-1],
  "5:17": [2, 15, 16],
  "5:18": [15, 32, 19, 13],
  "5:19": [19, 32],
  "5:20": [-1],
  "5:21": [19, 10, 32, 18],
  "5:22": [15, 17, 30, 26],
  "5:23": [10, 35, 2, 39],
  "5:24": [30, 26],
  "5:25": [26, 4],
  "5:26": [29, 30, 6, 13],
  "5:27": [29, 9],
  "5:28": [26, 28, 32, 3],
  "5:29": [2, 32],
  "5:30": [22, 33, 28, 1],
  "5:31": [17, 2, 18, 39],
  "5:32": [13, 1, 26, 24],
  "5:33": [15, 17, 13, 16],
  "5:34": [15, 13, 10, 1],
  "5:35": [15, 30],
  "5:36": [14, 1, 13],
  "5:37": [2, 36, 26, 18],
  "5:38": [14, 30, 28, 23],
  "5:39": [10, 26, 34, 2],

  // 6. Area of stationary
  "6:1": [-1],
  "6:2": [30, 2, 14, 18],
  "6:3": [-1],
  "6:4": [26, 7, 9, 39],
  "6:5": [-1],
  "6:6": [0],
  "6:7": [-1],
  "6:8": [-1],
  "6:9": [-1],
  "6:10": [1, 18, 35, 36],
  "6:11": [10, 15, 36, 37],
  "6:12": [-1],
  "6:13": [2, 38],
  "6:14": [40],
  "6:15": [-1],
  "6:16": [2, 10, 19, 30],
  "6:17": [35, 39, 38],
  "6:18": [-1],
  "6:19": [-1],
  "6:20": [-1],
  "6:21": [17, 32],
  "6:22": [17, 7, 30],
  "6:23": [10, 14, 18, 39],
  "6:24": [30, 16],
  "6:25": [10, 35, 4, 18],
  "6:26": [2, 18, 40, 4],
  "6:27": [32, 35, 40, 4],
  "6:28": [26, 28, 32, 3],
  "6:29": [2, 29, 18, 36],
  "6:30": [27, 2, 39, 35],
  "6:31": [22, 1, 40],
  "6:32": [40, 16],
  "6:33": [16, 4],
  "6:34": [16],
  "6:35": [15, 16],
  "6:36": [1, 18, 36],
  "6:37": [2, 35, 30, 18],
  "6:38": [23],
  "6:39": [10, 15, 17, 7],

  // 7. Volume of moving object
  "7:1": [2, 26, 29, 40],
  "7:2": [-1],
  "7:3": [1, 7, 4, 35],
  "7:4": [-1],
  "7:5": [1, 7, 4, 17],
  "7:6": [-1],
  "7:7": [0],
  "7:8": [-1],
  "7:9": [29, 4, 38, 34],
  "7:10": [15, 35, 36, 37],
  "7:11": [6, 35, 36, 37],
  "7:12": [1, 15, 29, 4],
  "7:13": [28, 10, 1, 39],
  "7:14": [9, 14, 15, 7],
  "7:15": [6, 35, 4],
  "7:16": [-1],
  "7:17": [34, 39, 10, 18],
  "7:18": [2, 13, 10],
  "7:19": [35],
  "7:20": [-1],
  "7:21": [35, 6, 13, 18],
  "7:22": [7, 15, 13, 16],
  "7:23": [36, 39, 34, 10],
  "7:24": [2, 22],
  "7:25": [2, 6, 34, 10],
  "7:26": [29, 30, 7],
  "7:27": [14, 1, 40, 11],
  "7:28": [25, 26, 28],
  "7:29": [25, 28, 2, 16],
  "7:30": [22, 21, 27, 35],
  "7:31": [17, 2, 40, 1],
  "7:32": [29, 1, 40],
  "7:33": [15, 13, 30, 12],
  "7:34": [10],
  "7:35": [15, 29],
  "7:36": [26, 1],
  "7:37": [29, 26, 4],
  "7:38": [35, 34, 16, 24],
  "7:39": [10, 6, 2, 34],

  // 8. Volume of stationary
  "8:1": [-1],
  "8:2": [35, 10, 19, 14],
  "8:3": [19, 14],
  "8:4": [35, 8, 2, 14],
  "8:5": [-1],
  "8:6": [-1],
  "8:7": [-1],
  "8:8": [0],
  "8:9": [-1],
  "8:10": [2, 18, 37],
  "8:11": [24, 35],
  "8:12": [7, 2, 35],
  "8:13": [34, 28, 35, 40],
  "8:14": [9, 14, 17, 15],
  "8:15": [-1],
  "8:16": [35, 34, 38],
  "8:17": [35, 6, 4],
  "8:18": [-1],
  "8:19": [-1],
  "8:20": [-1],
  "8:21": [30, 6],
  "8:22": [-1],
  "8:23": [10, 39, 35, 34],
  "8:24": [-1],
  "8:25": [35, 16, 32, 18],
  "8:26": [35, 3],
  "8:27": [2, 35, 16],
  "8:28": [-1],
  "8:29": [35, 10, 25],
  "8:30": [34, 39, 19, 27],
  "8:31": [30, 18, 35, 4],
  "8:32": [35],
  "8:33": [-1],
  "8:34": [1],
  "8:35": [-1],
  "8:36": [1, 31],
  "8:37": [2, 17, 26],
  "8:38": [-1],
  "8:39": [35, 37, 10, 2],

  // 9. Speed
  "9:1": [2, 28, 13, 38],
  "9:2": [-1],
  "9:3": [13, 14, 8],
  "9:4": [-1],
  "9:5": [29, 30, 34],
  "9:6": [-1],
  "9:7": [7, 29, 34],
  "9:8": [-1],
  "9:9": [0],
  "9:10": [13, 28, 15, 19],
  "9:11": [6, 18, 38, 40],
  "9:12": [35, 15, 18, 34],
  "9:13": [28, 33, 1, 18],
  "9:14": [8, 3, 26, 14],
  "9:15": [3, 19, 35, 5],
  "9:16": [-1],
  "9:17": [28, 30, 36, 2],
  "9:18": [10, 13, 19],
  "9:19": [8, 15, 35, 38],
  "9:20": [-1],
  "9:21": [19, 35, 38, 2],
  "9:22": [14, 20, 19, 35],
  "9:23": [10, 13, 28, 38],
  "9:24": [13, 26],
  "9:25": [-1],
  "9:26": [10, 19, 29, 38],
  "9:27": [11, 35, 27, 28],
  "9:28": [28, 32, 1, 24],
  "9:29": [10, 28, 32, 25],
  "9:30": [1, 28, 35, 23],
  "9:31": [2, 24, 35, 21],
  "9:32": [35, 13, 8, 1],
  "9:33": [32, 28, 13, 12],
  "9:34": [34, 2, 28, 27],
  "9:35": [15, 10, 26],
  "9:36": [10, 28, 4, 34],
  "9:37": [3, 34, 27, 16],
  "9:38": [10, 18],
  "9:39": [-1],

  // 10. Force (Intensity)
  "10:1": [8, 1, 37, 18],
  "10:2": [18, 13, 1, 28],
  "10:3": [17, 19, 9, 36],
  "10:4": [28, 10],
  "10:5": [19, 10, 15],
  "10:6": [1, 18, 36, 37],
  "10:7": [15, 9, 12, 37],
  "10:8": [2, 36, 18, 37],
  "10:9": [13, 28, 15, 12],
  "10:10": [0],
  "10:11": [18, 21, 11],
  "10:12": [10, 35, 40, 34],
  "10:13": [35, 10, 21],
  "10:14": [35, 10, 14, 27],
  "10:15": [19, 2],
  "10:16": [-1],
  "10:17": [35, 10, 21],
  "10:18": [-1],
  "10:19": [19, 17, 10],
  "10:20": [1, 16, 36, 37],
  "10:21": [19, 35, 18, 37],
  "10:22": [14, 15],
  "10:23": [8, 35, 40, 5],
  "10:24": [-1],
  "10:25": [10, 37, 36],
  "10:26": [14, 29, 18, 36],
  "10:27": [3, 35, 13, 21],
  "10:28": [35, 10, 23, 24],
  "10:29": [28, 29, 37, 36],
  "10:30": [1, 35, 40, 18],
  "10:31": [13, 3, 36, 24],
  "10:32": [15, 37, 18, 1],
  "10:33": [1, 28, 3, 25],
  "10:34": [15, 1, 11],
  "10:35": [15, 17, 18, 20],
  "10:36": [26, 35, 10, 18],
  "10:37": [36, 37, 10, 19],
  "10:38": [2, 35],
  "10:39": [3, 28, 35, 37],

  // 11. Stress or pressure
  "11:1": [10, 36, 37, 40],
  "11:2": [13, 29, 10, 18],
  "11:3": [35, 10, 36],
  "11:4": [35, 1, 14, 16],
  "11:5": [10, 15, 36, 28],
  "11:6": [10, 15, 36, 37],
  "11:7": [6, 35, 10],
  "11:8": [35, 24],
  "11:9": [6, 35, 36],
  "11:10": [36, 35, 21],
  "11:11": [0],
  "11:12": [35, 4, 15, 10],
  "11:13": [35, 33, 2, 40],
  "11:14": [9, 18, 3, 40],
  "11:15": [19, 3, 27],
  "11:16": [-1],
  "11:17": [35, 39, 19, 2],
  "11:18": [-1],
  "11:19": [14, 24, 10, 37],
  "11:20": [-1],
  "11:21": [10, 35, 14],
  "11:22": [2, 36, 25],
  "11:23": [10, 36, 3, 37],
  "11:24": [-1],
  "11:25": [37, 36, 4],
  "11:26": [10, 14, 36],
  "11:27": [10, 13, 19, 35],
  "11:28": [6, 28, 25],
  "11:29": [3, 35],
  "11:30": [22, 2, 37],
  "11:31": [2, 33, 27, 18],
  "11:32": [1, 35, 16],
  "11:33": [11],
  "11:34": [2],
  "11:35": [35],
  "11:36": [19, 1, 35],
  "11:37": [2, 36, 37],
  "11:38": [35, 24],
  "11:39": [10, 14, 35, 37],

  // 12. Shape
  "12:1": [8, 10, 29, 40],
  "12:2": [15, 10, 26, 3],
  "12:3": [29, 34, 5, 4],
  "12:4": [13, 14, 10, 7],
  "12:5": [5, 34, 4, 10],
  "12:6": [-1],
  "12:7": [14, 4, 15, 22],
  "12:8": [7, 2, 35],
  "12:9": [35, 15, 34, 18],
  "12:10": [35, 10, 37, 40],
  "12:11": [34, 15, 10, 14],
  "12:12": [0],
  "12:13": [33, 1, 18, 4],
  "12:14": [30, 14, 10, 40],
  "12:15": [14, 26, 9, 25],
  "12:16": [-1],
  "12:17": [22, 14, 19, 32],
  "12:18": [13, 15, 32],
  "12:19": [2, 6, 34, 14],
  "12:20": [-1],
  "12:21": [4, 6, 2],
  "12:22": [14],
  "12:23": [35, 29, 3, 5],
  "12:24": [-1],
  "12:25": [14, 10, 34, 17],
  "12:26": [36, 22],
  "12:27": [10, 40, 16],
  "12:28": [28, 32, 1],
  "12:29": [32, 30, 40],
  "12:30": [22, 1, 2, 35],
  "12:31": [35, 1],
  "12:32": [1, 32, 17, 28],
  "12:33": [32, 15, 26],
  "12:34": [2, 13, 1],
  "12:35": [1, 15, 29],
  "12:36": [16, 29, 1, 28],
  "12:37": [15, 13, 39],
  "12:38": [15, 1, 32],
  "12:39": [17, 26, 34, 10],

  // 13. Stability of the object
  "13:1": [21, 35, 2, 39],
  "13:2": [26, 39, 1, 40],
  "13:3": [13, 15, 1, 28],
  "13:4": [37],
  "13:5": [2, 11, 13],
  "13:6": [39],
  "13:7": [28, 10, 19, 39],
  "13:8": [34, 28, 35, 40],
  "13:9": [33, 15, 28, 18],
  "13:10": [10, 35, 21, 16],
  "13:11": [2, 35, 40],
  "13:12": [22, 1, 18, 4],
  "13:13": [0],
  "13:14": [17, 9, 15],
  "13:15": [13, 27, 10, 35],
  "13:16": [39, 3, 35, 23],
  "13:17": [35, 1, 32],
  "13:18": [32, 3, 27, 16],
  "13:19": [13, 19],
  "13:20": [27, 4, 29, 18],
  "13:21": [32, 35, 27, 31],
  "13:22": [14, 2, 39, 6],
  "13:23": [2, 14, 30, 40],
  "13:24": [-1],
  "13:25": [35, 27],
  "13:26": [15, 32, 35],
  "13:27": [-1],
  "13:28": [13],
  "13:29": [18],
  "13:30": [35, 24, 30, 18],
  "13:31": [35, 40, 27, 39],
  "13:32": [35, 19],
  "13:33": [32, 35, 30],
  "13:34": [2, 35, 10, 16],
  "13:35": [35, 30, 34, 2],
  "13:36": [2, 35, 22, 26],
  "13:37": [35, 22, 39, 23],
  "13:38": [1, 8, 35],
  "13:39": [23, 35, 40, 3],

  // 14. Strength
  "14:1": [1, 8, 40, 15],
  "14:2": [40, 26, 27, 1],
  "14:3": [1, 15, 8, 35],
  "14:4": [15, 14, 28, 26],
  "14:5": [3, 34, 40, 29],
  "14:6": [9, 40, 28],
  "14:7": [10, 15, 14, 7],
  "14:8": [9, 14, 17, 15],
  "14:9": [8, 13, 26, 14],
  "14:10": [10, 18, 3, 14],
  "14:11": [10, 3, 18, 40],
  "14:12": [10, 30, 35, 40],
  "14:13": [13, 17, 35],
  "14:14": [0],
  "14:15": [27, 3, 26],
  "14:16": [-1],
  "14:17": [30, 10, 40],
  "14:18": [35, 19],
  "14:19": [19, 35, 10],
  "14:20": [35],
  "14:21": [10, 26, 35, 28],
  "14:22": [35],
  "14:23": [35, 28, 31, 40],
  "14:24": [-1],
  "14:25": [29, 3, 28, 10],
  "14:26": [29, 10, 27],
  "14:27": [11, 3],
  "14:28": [3, 27, 16],
  "14:29": [3, 27],
  "14:30": [18, 35, 37, 1],
  "14:31": [15, 35, 22, 2],
  "14:32": [11, 3, 10, 32],
  "14:33": [32, 40, 25, 2],
  "14:34": [27, 11, 3],
  "14:35": [15, 3, 32],
  "14:36": [2, 13, 25, 28],
  "14:37": [27, 3, 15, 40],
  "14:38": [15],
  "14:39": [29, 35, 10, 14],

  // 15. Durability of moving obj.
  "15:1": [19, 5, 34, 31],
  "15:2": [-1],
  "15:3": [2, 19, 9],
  "15:4": [-1],
  "15:5": [3, 17, 19],
  "15:6": [-1],
  "15:7": [10, 2, 19, 30],
  "15:8": [-1],
  "15:9": [3, 35, 5],
  "15:10": [19, 2, 16],
  "15:11": [19, 3, 27],
  "15:12": [14, 26, 28, 25],
  "15:13": [13, 3, 35],
  "15:14": [27, 3, 10],
  "15:15": [0],
  "15:16": [-1],
  "15:17": [19, 35, 39],
  "15:18": [2, 19, 4, 35],
  "15:19": [28, 6, 35, 18],
  "15:20": [-1],
  "15:21": [19, 10, 35, 38],
  "15:22": [-1],
  "15:23": [28, 27, 3, 18],
  "15:24": [10],
  "15:25": [20, 10, 28, 18],
  "15:26": [3, 35, 10, 40],
  "15:27": [11, 2, 13],
  "15:28": [3],
  "15:29": [3, 27, 16, 40],
  "15:30": [22, 15, 33, 28],
  "15:31": [21, 39, 16, 22],
  "15:32": [27, 1, 4],
  "15:33": [12, 27],
  "15:34": [29, 10, 27],
  "15:35": [1, 35, 13],
  "15:36": [10, 4, 29, 15],
  "15:37": [19, 29, 39, 35],
  "15:38": [6, 10],
  "15:39": [35, 17, 14, 19],

  // 16. Durability of non moving obj.
  "16:1": [-1],
  "16:2": [6, 27, 19, 16],
  "16:3": [-1],
  "16:4": [1, 40, 35],
  "16:5": [-1],
  "16:6": [-1],
  "16:7": [-1],
  "16:8": [35, 34, 38],
  "16:9": [-1],
  "16:10": [-1],
  "16:11": [-1],
  "16:12": [-1],
  "16:13": [39, 3, 35, 23],
  "16:14": [-1],
  "16:15": [-1],
  "16:16": [0],
  "16:17": [19, 18, 36, 40],
  "16:18": [-1],
  "16:19": [-1],
  "16:20": [-1],
  "16:21": [16],
  "16:22": [-1],
  "16:23": [27, 16, 18, 38],
  "16:24": [10],
  "16:25": [28, 20, 10, 16],
  "16:26": [3, 35, 31],
  "16:27": [34, 27, 6, 40],
  "16:28": [10, 26, 24],
  "16:29": [-1],
  "16:30": [17, 1, 40, 33],
  "16:31": [22],
  "16:32": [35, 10],
  "16:33": [1],
  "16:34": [1],
  "16:35": [2],
  "16:36": [-1],
  "16:37": [25, 34, 6, 35],
  "16:38": [1],
  "16:39": [20, 10, 16, 38],

  // 17. Temperature
  "17:1": [36, 22, 6, 38],
  "17:2": [22, 35, 32],
  "17:3": [15, 19, 9],
  "17:4": [15, 19, 9],
  "17:5": [3, 35, 39, 18],
  "17:6": [35, 38],
  "17:7": [34, 39, 40, 18],
  "17:8": [35, 6, 4],
  "17:9": [2, 28, 36, 30],
  "17:10": [35, 10, 3, 21],
  "17:11": [35, 39, 19, 2],
  "17:12": [14, 22, 19, 32],
  "17:13": [1, 35, 32],
  "17:14": [10, 30, 22, 40],
  "17:15": [19, 13, 39],
  "17:16": [19, 18, 36, 40],
  "17:17": [0],
  "17:18": [32, 30, 21, 16],
  "17:19": [19, 15, 3, 17],
  "17:20": [-1],
  "17:21": [2, 14, 17, 25],
  "17:22": [21, 17, 35, 38],
  "17:23": [21, 36, 29, 31],
  "17:24": [-1],
  "17:25": [35, 28, 21, 18],
  "17:26": [3, 17, 30, 39],
  "17:27": [19, 35, 3, 10],
  "17:28": [32, 19, 24],
  "17:29": [24],
  "17:30": [22, 33, 35, 2],
  "17:31": [22, 35, 2, 24],
  "17:32": [26, 27],
  "17:33": [26, 27],
  "17:34": [4, 10, 16],
  "17:35": [2, 18, 27],
  "17:36": [2, 17, 16],
  "17:37": [3, 27, 35, 31],
  "17:38": [26, 2, 19, 16],
  "17:39": [15, 28, 35],

  // 18. Illumination intensity
  "18:1": [19, 1, 32],
  "18:2": [2, 35, 32],
  "18:3": [19, 32, 16],
  "18:4": [-1],
  "18:5": [19, 32, 26],
  "18:6": [-1],
  "18:7": [2, 13, 10],
  "18:8": [-1],
  "18:9": [10, 13, 19],
  "18:10": [26, 19, 6],
  "18:11": [-1],
  "18:12": [32, 30],
  "18:13": [32, 3, 27],
  "18:14": [35, 19],
  "18:15": [2, 19, 6],
  "18:16": [-1],
  "18:17": [32, 35, 19],
  "18:18": [0],
  "18:19": [32, 1, 19],
  "18:20": [32, 35, 1, 15],
  "18:21": [32],
  "18:22": [13, 16, 1, 6],
  "18:23": [13, 1],
  "18:24": [1, 6],
  "18:25": [19, 1, 26, 17],
  "18:26": [1, 19],
  "18:27": [-1],
  "18:28": [11, 15, 32],
  "18:29": [3, 32],
  "18:30": [15, 19],
  "18:31": [35, 19, 32, 39],
  "18:32": [19, 35, 28, 26],
  "18:33": [28, 26, 19],
  "18:34": [15, 17, 13, 16],
  "18:35": [15, 1, 19],
  "18:36": [6, 32, 13],
  "18:37": [32, 15],
  "18:38": [2, 26, 10],
  "18:39": [2, 25, 16],

  // 19. Use of energy by moving
  "19:1": [12, 18, 28, 31],
  "19:2": [-1],
  "19:3": [12, 28],
  "19:4": [-1],
  "19:5": [15, 19, 25],
  "19:6": [-1],
  "19:7": [35, 13, 18],
  "19:8": [-1],
  "19:9": [8, 35],
  "19:10": [16, 26, 21, 2],
  "19:11": [23, 14, 25],
  "19:12": [12, 2, 29],
  "19:13": [19, 13, 17, 24],
  "19:14": [5, 19, 9, 35],
  "19:15": [28, 35, 6, 18],
  "19:16": [-1],
  "19:17": [19, 24, 3, 14],
  "19:18": [2, 15, 19],
  "19:19": [0],
  "19:20": [-1],
  "19:21": [6, 19, 37, 18],
  "19:22": [12, 22, 15, 24],
  "19:23": [35, 24, 18, 5],
  "19:24": [-1],
  "19:25": [35, 38, 19, 18],
  "19:26": [34, 23, 16, 18],
  "19:27": [19, 21, 11, 27],
  "19:28": [3, 1, 32],
  "19:29": [-1],
  "19:30": [1, 35, 6, 27],
  "19:31": [2, 35, 6],
  "19:32": [28, 26, 30],
  "19:33": [19, 35],
  "19:34": [1, 15, 17, 28],
  "19:35": [15, 17, 13, 16],
  "19:36": [2, 29, 27, 28],
  "19:37": [35, 38],
  "19:38": [32, 2],
  "19:39": [12, 28, 35],

  // 20. Use of energy by stationary
  "20:1": [-1],
  "20:2": [19, 9, 6, 27],
  "20:3": [-1],
  "20:4": [-1],
  "20:5": [-1],
  "20:6": [-1],
  "20:7": [-1],
  "20:8": [-1],
  "20:9": [-1],
  "20:10": [36, 37],
  "20:11": [-1],
  "20:12": [-1],
  "20:13": [27, 4, 29, 18],
  "20:14": [35],
  "20:15": [-1],
  "20:16": [-1],
  "20:17": [-1],
  "20:18": [19, 2, 35, 32],
  "20:19": [-1],
  "20:20": [0],
  "20:21": [-1],
  "20:22": [-1],
  "20:23": [28, 27, 18, 31],
  "20:24": [-1],
  "20:25": [-1],
  "20:26": [3, 35, 31],
  "20:27": [10, 36, 23],
  "20:28": [-1],
  "20:29": [-1],
  "20:30": [10, 2, 22, 37],
  "20:31": [19, 22, 18],
  "20:32": [1, 4],
  "20:33": [-1],
  "20:34": [-1],
  "20:35": [-1],
  "20:36": [-1],
  "20:37": [19, 35, 16, 25],
  "20:38": [-1],
  "20:39": [1, 6],

  // 21. Power
  "21:1": [8, 36, 38, 31],
  "21:2": [19, 26, 17, 27],
  "21:3": [1, 10, 35, 37],
  "21:4": [-1],
  "21:5": [19, 38],
  "21:6": [17, 32, 13, 38],
  "21:7": [35, 6, 38],
  "21:8": [30, 6, 25],
  "21:9": [15, 35, 2],
  "21:10": [26, 2, 36, 35],
  "21:11": [22, 10, 35],
  "21:12": [29, 14, 2, 40],
  "21:13": [35, 32, 15, 31],
  "21:14": [26, 10, 28],
  "21:15": [19, 35, 10, 38],
  "21:16": [16],
  "21:17": [2, 14, 17, 25],
  "21:18": [16, 6, 19],
  "21:19": [16, 6, 19, 37],
  "21:20": [-1],
  "21:21": [0],
  "21:22": [10, 35, 38],
  "21:23": [28, 27, 18, 38],
  "21:24": [10, 19],
  "21:25": [35, 20, 10, 6],
  "21:26": [4, 34, 19],
  "21:27": [19, 24, 26, 31],
  "21:28": [32, 15, 2],
  "21:29": [32, 2],
  "21:30": [19, 22, 31, 2],
  "21:31": [2, 35, 18],
  "21:32": [26, 10, 34],
  "21:33": [26, 35, 10],
  "21:34": [35, 2, 10, 34],
  "21:35": [19, 17, 34],
  "21:36": [20, 19, 30, 34],
  "21:37": [19, 35, 16],
  "21:38": [28, 2, 17],
  "21:39": [28, 35, 34],

  // 22. Loss of Energy
  "22:1": [15, 6, 19, 28],
  "22:2": [19, 6, 18, 9],
  "22:3": [7, 2, 6, 13],
  "22:4": [6, 38, 7],
  "22:5": [15, 26, 17, 30],
  "22:6": [17, 7, 30, 18],
  "22:7": [7, 18, 23],
  "22:8": [7],
  "22:9": [16, 35, 38],
  "22:10": [36, 38],
  "22:11": [-1],
  "22:12": [-1],
  "22:13": [14, 2, 39, 6],
  "22:14": [26],
  "22:15": [-1],
  "22:16": [-1],
  "22:17": [19, 38, 7],
  "22:18": [1, 13, 32, 15],
  "22:19": [-1],
  "22:20": [-1],
  "22:21": [3, 38],
  "22:22": [0],
  "22:23": [35, 27, 2, 37],
  "22:24": [19, 10],
  "22:25": [10, 18, 32, 7],
  "22:26": [7, 18, 25],
  "22:27": [11, 10, 35],
  "22:28": [32],
  "22:29": [-1],
  "22:30": [21, 22, 35, 2],
  "22:31": [21, 35, 2, 22],
  "22:32": [-1],
  "22:33": [35, 32, 1],
  "22:34": [2, 19],
  "22:35": [-1],
  "22:36": [7, 23],
  "22:37": [35, 3, 15, 23],
  "22:38": [2],
  "22:39": [28, 10, 29, 35],

  // 23. Loss of substance
  "23:1": [35, 6, 23, 40],
  "23:2": [35, 6, 22, 32],
  "23:3": [14, 29, 10, 39],
  "23:4": [10, 28, 24],
  "23:5": [35, 2, 10, 31],
  "23:6": [10, 18, 39, 31],
  "23:7": [1, 29, 30, 36],
  "23:8": [3, 39, 18, 31],
  "23:9": [10, 13, 28, 38],
  "23:10": [14, 15, 18, 40],
  "23:11": [3, 36, 37, 10],
  "23:12": [29, 35, 3, 5],
  "23:13": [2, 14, 30, 40],
  "23:14": [35, 28, 31, 40],
  "23:15": [28, 27, 3, 18],
  "23:16": [27, 16, 18, 38],
  "23:17": [21, 36, 39, 31],
  "23:18": [1, 6, 13],
  "23:19": [35, 18, 24, 5],
  "23:20": [28, 27, 12, 31],
  "23:21": [28, 27, 18, 38],
  "23:22": [35, 27, 2, 31],
  "23:23": [0],
  "23:24": [-1],
  "23:25": [15, 18, 35, 10],
  "23:26": [6, 3, 10, 24],
  "23:27": [10, 29, 39, 35],
  "23:28": [16, 34, 31, 28],
  "23:29": [35, 10, 24, 31],
  "23:30": [33, 22, 30, 40],
  "23:31": [10, 1, 34, 29],
  "23:32": [15, 34, 33],
  "23:33": [32, 28, 2, 24],
  "23:34": [2, 35, 34, 27],
  "23:35": [15, 10, 2],
  "23:36": [35, 10, 28, 24],
  "23:37": [35, 18, 10, 13],
  "23:38": [35, 10, 18],
  "23:39": [28, 35, 10, 23],

  // 24. Loss of Information
  "24:1": [10, 24, 35],
  "24:2": [10, 35, 5],
  "24:3": [1, 26],
  "24:4": [26],
  "24:5": [30, 26],
  "24:6": [30, 16],
  "24:7": [-1],
  "24:8": [2, 22],
  "24:9": [26, 32],
  "24:10": [-1],
  "24:11": [-1],
  "24:12": [-1],
  "24:13": [-1],
  "24:14": [-1],
  "24:15": [10],
  "24:16": [10],
  "24:17": [-1],
  "24:18": [19],
  "24:19": [-1],
  "24:20": [-1],
  "24:21": [10, 19],
  "24:22": [19, 10],
  "24:23": [-1],
  "24:24": [0],
  "24:25": [24, 26, 28, 32],
  "24:26": [24, 28, 35],
  "24:27": [10, 28, 23],
  "24:28": [-1],
  "24:29": [-1],
  "24:30": [22, 10, 1],
  "24:31": [10, 21, 22],
  "24:32": [32],
  "24:33": [27, 22],
  "24:34": [-1],
  "24:35": [-1],
  "24:36": [-1],
  "24:37": [35, 33],
  "24:38": [35],
  "24:39": [13, 23, 15],

  // 25. Loss of Time
  "25:1": [10, 20, 37, 35],
  "25:2": [10, 20, 26, 5],
  "25:3": [15, 2, 29],
  "25:4": [30, 24, 14, 5],
  "25:5": [26, 4, 5, 16],
  "25:6": [10, 35, 17, 4],
  "25:7": [2, 5, 34, 10],
  "25:8": [35, 16, 32, 18],
  "25:9": [-1],
  "25:10": [10, 37, 36, 5],
  "25:11": [37, 36, 4],
  "25:12": [4, 10, 34, 17],
  "25:13": [35, 3, 22, 5],
  "25:14": [29, 3, 28, 18],
  "25:15": [20, 10, 28, 18],
  "25:16": [28, 20, 10, 16],
  "25:17": [35, 29, 21, 18],
  "25:18": [1, 19, 26, 17],
  "25:19": [35, 38, 19, 18],
  "25:20": [1],
  "25:21": [35, 20, 10, 6],
  "25:22": [10, 5, 18, 32],
  "25:23": [35, 18, 10, 39],
  "25:24": [24, 26, 28, 32],
  "25:25": [0],
  "25:26": [35, 38, 18, 16],
  "25:27": [10, 30, 4],
  "25:28": [24, 34, 28, 32],
  "25:29": [24, 26, 28, 18],
  "25:30": [35, 18, 34],
  "25:31": [35, 22, 18, 39],
  "25:32": [35, 28, 34, 4],
  "25:33": [4, 28, 10, 34],
  "25:34": [32, 1, 10],
  "25:35": [35, 28],
  "25:36": [6, 29],
  "25:37": [18, 28, 32, 10],
  "25:38": [24, 28, 35, 30],
  "25:39": [-1],

  // 26. Quantity of substance/the
  "26:1": [35, 6, 18, 31],
  "26:2": [27, 26, 18, 35],
  "26:3": [29, 14, 35, 18],
  "26:4": [-1],
  "26:5": [15, 14, 29],
  "26:6": [2, 18, 40, 4],
  "26:7": [15, 20, 29],
  "26:8": [-1],
  "26:9": [35, 29, 34, 28],
  "26:10": [35, 14, 3],
  "26:11": [10, 36, 14, 3],
  "26:12": [35, 14],
  "26:13": [15, 2, 17, 40],
  "26:14": [14, 35, 34, 10],
  "26:15": [3, 35, 10, 40],
  "26:16": [3, 35, 31],
  "26:17": [3, 17, 39],
  "26:18": [-1],
  "26:19": [34, 29, 16, 18],
  "26:20": [3, 35, 31],
  "26:21": [35],
  "26:22": [7, 18, 25],
  "26:23": [6, 3, 10, 24],
  "26:24": [24, 28, 35],
  "26:25": [35, 38, 18, 16],
  "26:26": [0],
  "26:27": [18, 3, 28, 40],
  "26:28": [13, 2, 28],
  "26:29": [33, 30],
  "26:30": [35, 33, 29, 31],
  "26:31": [3, 35, 40, 39],
  "26:32": [29, 1, 35, 27],
  "26:33": [35, 29, 25, 10],
  "26:34": [2, 32, 10, 25],
  "26:35": [15, 3, 29],
  "26:36": [3, 13, 27, 10],
  "26:37": [3, 27, 29, 18],
  "26:38": [8, 35],
  "26:39": [13, 29, 3, 27],

  // 27. Reliability
  "27:1": [3, 8, 10, 40],
  "27:2": [3, 10, 8, 28],
  "27:3": [15, 9, 14, 4],
  "27:4": [15, 29, 28, 11],
  "27:5": [17, 10, 14, 16],
  "27:6": [32, 35, 40, 4],
  "27:7": [3, 10, 14, 24],
  "27:8": [2, 35, 24],
  "27:9": [21, 35, 11, 28],
  "27:10": [8, 28, 10, 3],
  "27:11": [10, 24, 35, 19],
  "27:12": [35, 1, 16, 11],
  "27:13": [-1],
  "27:14": [11, 28],
  "27:15": [2, 35, 3, 25],
  "27:16": [34, 27, 6, 40],
  "27:17": [3, 35, 10],
  "27:18": [11, 32, 13],
  "27:19": [21, 11, 27, 19],
  "27:20": [36, 23],
  "27:21": [21, 11, 26, 31],
  "27:22": [10, 11, 35],
  "27:23": [10, 35, 29, 39],
  "27:24": [10, 28],
  "27:25": [10, 30, 4],
  "27:26": [21, 28, 40, 3],
  "27:27": [0],
  "27:28": [32, 3, 11, 23],
  "27:29": [11, 32, 1],
  "27:30": [27, 35, 2, 40],
  "27:31": [35, 2, 40, 26],
  "27:32": [-1],
  "27:33": [27, 17, 40],
  "27:34": [1, 11],
  "27:35": [13, 35, 8, 24],
  "27:36": [13, 35, 1],
  "27:37": [27, 40, 28],
  "27:38": [11, 13, 27],
  "27:39": [1, 35, 29, 38],

  // 28. Measurement accuracy
  "28:1": [32, 35, 26, 28],
  "28:2": [28, 35, 25, 26],
  "28:3": [28, 26, 5, 16],
  "28:4": [32, 28, 3, 16],
  "28:5": [26, 28, 32, 3],
  "28:6": [26, 28, 32, 3],
  "28:7": [32, 13, 6],
  "28:8": [-1],
  "28:9": [28, 13, 32, 24],
  "28:10": [32, 2],
  "28:11": [6, 28, 32],
  "28:12": [6, 28, 32],
  "28:13": [32, 35, 13],
  "28:14": [28, 6, 32],
  "28:15": [28, 6, 32],
  "28:16": [10, 26, 24],
  "28:17": [6, 19, 28, 24],
  "28:18": [6, 1, 32],
  "28:19": [3, 6, 32],
  "28:20": [-1],
  "28:21": [3, 6, 32],
  "28:22": [26, 32, 27],
  "28:23": [10, 16, 31, 28],
  "28:24": [-1],
  "28:25": [24, 34, 28, 32],
  "28:26": [2, 6, 32],
  "28:27": [5, 11, 1, 23],
  "28:28": [0],
  "28:29": [-1],
  "28:30": [28, 24, 22, 26],
  "28:31": [3, 33, 39, 10],
  "28:32": [6, 35, 25, 18],
  "28:33": [1, 13, 17, 34],
  "28:34": [1, 32, 13, 11],
  "28:35": [13, 35, 2],
  "28:36": [27, 35, 10, 34],
  "28:37": [26, 24, 32, 28],
  "28:38": [28, 2, 10, 34],
  "28:39": [10, 34, 28, 32],

  // 29. Manufacturing precision
  "29:1": [28, 32, 13, 18],
  "29:2": [28, 35, 27, 9],
  "29:3": [10, 28, 29, 37],
  "29:4": [2, 32, 10],
  "29:5": [28, 33, 29, 32],
  "29:6": [2, 29, 18, 36],
  "29:7": [32, 23, 2],
  "29:8": [25, 10, 35],
  "29:9": [10, 28, 32],
  "29:10": [28, 19, 34, 36],
  "29:11": [3, 35],
  "29:12": [32, 30, 40],
  "29:13": [30, 18],
  "29:14": [3, 27],
  "29:15": [3, 27, 40],
  "29:16": [-1],
  "29:17": [19, 26],
  "29:18": [3, 32],
  "29:19": [32, 2],
  "29:20": [-1],
  "29:21": [32, 2],
  "29:22": [13, 32, 2],
  "29:23": [35, 31, 10, 24],
  "29:24": [-1],
  "29:25": [32, 26, 28, 18],
  "29:26": [32, 30],
  "29:27": [11, 32, 1],
  "29:28": [-1],
  "29:29": [0],
  "29:30": [26, 28, 10, 36],
  "29:31": [4, 17, 34, 26],
  "29:32": [-1],
  "29:33": [1, 32, 35, 23],
  "29:34": [25, 10],
  "29:35": [-1],
  "29:36": [26, 2, 18],
  "29:37": [-1],
  "29:38": [26, 28, 18, 23],
  "29:39": [10, 18, 32, 39],

  // 30. Object-affected harmful
  "30:1": [22, 21, 27, 39],
  "30:2": [2, 22, 13, 24],
  "30:3": [17, 1, 39, 4],
  "30:4": [1, 18],
  "30:5": [22, 1, 33, 28],
  "30:6": [27, 2, 39, 35],
  "30:7": [22, 23, 37, 35],
  "30:8": [34, 39, 19, 27],
  "30:9": [21, 22, 35, 28],
  "30:10": [13, 35, 39, 18],
  "30:11": [22, 2, 37],
  "30:12": [22, 1, 3, 35],
  "30:13": [35, 24, 30, 18],
  "30:14": [18, 35, 37, 1],
  "30:15": [22, 15, 33, 28],
  "30:16": [17, 1, 40, 33],
  "30:17": [22, 33, 35, 2],
  "30:18": [1, 19, 32, 13],
  "30:19": [1, 24, 6, 27],
  "30:20": [10, 2, 22, 37],
  "30:21": [19, 22, 31, 2],
  "30:22": [21, 22, 35, 2],
  "30:23": [33, 22, 19, 40],
  "30:24": [22, 10, 2],
  "30:25": [35, 18, 34],
  "30:26": [35, 33, 29, 31],
  "30:27": [27, 24, 2, 40],
  "30:28": [28, 33, 23, 26],
  "30:29": [26, 28, 10, 18],
  "30:30": [0],
  "30:31": [-1],
  "30:32": [24, 35, 2],
  "30:33": [2, 25, 28, 39],
  "30:34": [35, 10, 2],
  "30:35": [35, 11, 22, 31],
  "30:36": [22, 19, 29, 40],
  "30:37": [22, 19, 29, 40],
  "30:38": [33, 3, 34],
  "30:39": [22, 35, 13, 24],

  // 31. Object-generated harmful
  "31:1": [19, 22, 15, 39],
  "31:2": [35, 22, 1, 39],
  "31:3": [17, 15, 16, 22],
  "31:4": [-1],
  "31:5": [17, 2, 18, 39],
  "31:6": [22, 1, 40],
  "31:7": [17, 2, 40],
  "31:8": [30, 18, 35, 4],
  "31:9": [35, 28, 3, 23],
  "31:10": [35, 28, 1, 40],
  "31:11": [2, 33, 27, 18],
  "31:12": [35, 1],
  "31:13": [35, 40, 27, 39],
  "31:14": [15, 35, 22, 2],
  "31:15": [15, 22, 33, 31],
  "31:16": [21, 39, 16, 22],
  "31:17": [22, 35, 2, 24],
  "31:18": [19, 24, 39, 32],
  "31:19": [2, 35, 6],
  "31:20": [19, 22, 18],
  "31:21": [2, 35, 18],
  "31:22": [21, 35, 2, 22],
  "31:23": [10, 1, 34],
  "31:24": [10, 21, 29],
  "31:25": [1, 22],
  "31:26": [3, 24, 39, 1],
  "31:27": [24, 2, 40, 39],
  "31:28": [3, 33, 26],
  "31:29": [4, 17, 34, 26],
  "31:30": [-1],
  "31:31": [0],
  "31:32": [-1],
  "31:33": [-1],
  "31:34": [-1],
  "31:35": [-1],
  "31:36": [19, 1, 31],
  "31:37": [2, 21, 27, 1],
  "31:38": [2],
  "31:39": [22, 35, 18, 39],

  // 32. Ease of manufacture
  "32:1": [28, 29, 15, 16],
  "32:2": [1, 27, 36, 13],
  "32:3": [1, 29, 13, 17],
  "32:4": [15, 17, 27],
  "32:5": [13, 1, 26, 12],
  "32:6": [16, 40],
  "32:7": [13, 29, 1, 40],
  "32:8": [35],
  "32:9": [35, 13, 8, 1],
  "32:10": [35, 12],
  "32:11": [35, 19, 1, 37],
  "32:12": [1, 28, 13, 27],
  "32:13": [11, 13, 1],
  "32:14": [1, 3, 10, 32],
  "32:15": [27, 1, 4],
  "32:16": [35, 16],
  "32:17": [27, 26, 18],
  "32:18": [28, 24, 27, 1],
  "32:19": [28, 26, 27, 1],
  "32:20": [1, 4],
  "32:21": [27, 1, 12, 24],
  "32:22": [19, 35],
  "32:23": [15, 34, 33],
  "32:24": [32, 24, 18, 16],
  "32:25": [35, 28, 34, 4],
  "32:26": [35, 23, 1, 24],
  "32:27": [-1],
  "32:28": [1, 35, 12, 18],
  "32:29": [-1],
  "32:30": [24, 2],
  "32:31": [-1],
  "32:32": [0],
  "32:33": [2, 5, 13, 16],
  "32:34": [35, 1, 11, 9],
  "32:35": [2, 13, 15],
  "32:36": [27, 26, 1],
  "32:37": [6, 28, 11, 1],
  "32:38": [8, 28, 1],
  "32:39": [35, 1, 10, 28],

  // 33. Ease of operation
  "33:1": [25, 2, 13, 15],
  "33:2": [6, 13, 1, 25],
  "33:3": [1, 17, 13, 12],
  "33:4": [-1],
  "33:5": [1, 17, 13, 16],
  "33:6": [18, 16, 15, 39],
  "33:7": [1, 16, 35, 15],
  "33:8": [4, 18, 39, 31],
  "33:9": [18, 13, 34],
  "33:10": [28, 13, 35],
  "33:11": [2, 32, 12],
  "33:12": [15, 34, 29, 28],
  "33:13": [32, 35, 30],
  "33:14": [32, 40, 3, 28],
  "33:15": [29, 3, 8, 25],
  "33:16": [1, 16, 25],
  "33:17": [26, 27, 13],
  "33:18": [13, 17, 1, 24],
  "33:19": [1, 13, 24],
  "33:20": [-1],
  "33:21": [35, 34, 2, 10],
  "33:22": [2, 19, 13],
  "33:23": [28, 32, 2, 24],
  "33:24": [4, 10, 27, 22],
  "33:25": [4, 28, 10, 34],
  "33:26": [12, 35],
  "33:27": [17, 27, 8, 40],
  "33:28": [25, 13, 2, 34],
  "33:29": [1, 32, 35, 23],
  "33:30": [2, 25, 28, 39],
  "33:31": [-1],
  "33:32": [2, 5, 12],
  "33:33": [0],
  "33:34": [12, 26, 1, 32],
  "33:35": [15, 34, 1, 16],
  "33:36": [32, 26, 12, 17],
  "33:37": [-1],
  "33:38": [1, 34, 12, 3],
  "33:39": [15, 1, 28],

  // 34. Ease of repair
  "34:1": [2, 27, 35, 11],
  "34:2": [2, 27, 35, 11],
  "34:3": [1, 28, 10, 25],
  "34:4": [3, 18, 31],
  "34:5": [15, 13, 32],
  "34:6": [16, 25],
  "34:7": [25, 2, 35, 11],
  "34:8": [1],
  "34:9": [34, 9],
  "34:10": [1, 11, 10],
  "34:11": [13],
  "34:12": [1, 13, 2, 4],
  "34:13": [2, 35],
  "34:14": [11, 1, 2, 9],
  "34:15": [11, 29, 28, 27],
  "34:16": [1],
  "34:17": [4, 10],
  "34:18": [15, 1, 13],
  "34:19": [15, 1, 28, 16],
  "34:20": [-1],
  "34:21": [15, 10, 32, 2],
  "34:22": [15, 1, 32, 19],
  "34:23": [2, 35, 34, 27],
  "34:24": [-1],
  "34:25": [32, 1, 10, 25],
  "34:26": [2, 28, 10, 25],
  "34:27": [11, 10, 1, 16],
  "34:28": [10, 2, 13],
  "34:29": [25, 10],
  "34:30": [35, 10, 2, 16],
  "34:31": [-1],
  "34:32": [1, 35, 11, 10],
  "34:33": [1, 12, 26, 15],
  "34:34": [0],
  "34:35": [7, 1, 4, 16],
  "34:36": [35, 1, 13, 11],
  "34:37": [-1],
  "34:38": [34, 35, 7, 13],
  "34:39": [1, 32, 10],

  // 35. Adaptability or versatility
  "35:1": [1, 6, 15, 8],
  "35:2": [19, 15, 29, 16],
  "35:3": [35, 1, 29, 2],
  "35:4": [1, 35, 16],
  "35:5": [35, 30, 29, 7],
  "35:6": [15, 16],
  "35:7": [15, 35, 29],
  "35:8": [-1],
  "35:9": [35, 10, 14],
  "35:10": [15, 17, 20],
  "35:11": [35, 16],
  "35:12": [15, 37, 1, 8],
  "35:13": [35, 30, 14],
  "35:14": [35, 3, 32, 6],
  "35:15": [13, 1, 35],
  "35:16": [2, 16],
  "35:17": [27, 2, 3, 35],
  "35:18": [6, 22, 26, 1],
  "35:19": [19, 35, 29, 13],
  "35:20": [-1],
  "35:21": [19, 1, 29],
  "35:22": [18, 15, 1],
  "35:23": [15, 10, 2, 13],
  "35:24": [-1],
  "35:25": [35, 28],
  "35:26": [3, 35, 15],
  "35:27": [35, 13, 8, 24],
  "35:28": [35, 5, 1, 10],
  "35:29": [-1],
  "35:30": [35, 11, 32, 31],
  "35:31": [-1],
  "35:32": [1, 13, 31],
  "35:33": [15, 34, 1, 16],
  "35:34": [1, 16, 7, 4],
  "35:35": [0],
  "35:36": [15, 29, 37, 28],
  "35:37": [1],
  "35:38": [27, 34, 35],
  "35:39": [35, 28, 6, 37],

  // 36. Device complexity
  "36:1": [26, 30, 34, 36],
  "36:2": [2, 26, 35, 39],
  "36:3": [1, 19, 26, 24],
  "36:4": [26],
  "36:5": [14, 1, 13, 16],
  "36:6": [6, 36],
  "36:7": [34, 26, 6],
  "36:8": [1, 16],
  "36:9": [34, 10, 28],
  "36:10": [26, 16],
  "36:11": [19, 1, 35],
  "36:12": [29, 13, 28, 15],
  "36:13": [2, 22, 17, 19],
  "36:14": [2, 13, 28],
  "36:15": [10, 4, 28, 15],
  "36:16": [-1],
  "36:17": [2, 17, 13],
  "36:18": [24, 17, 13],
  "36:19": [27, 2, 29, 28],
  "36:20": [-1],
  "36:21": [20, 19, 30, 34],
  "36:22": [10, 35, 13, 2],
  "36:23": [35, 10, 28, 29],
  "36:24": [-1],
  "36:25": [6, 29],
  "36:26": [13, 3, 27, 10],
  "36:27": [13, 35, 1],
  "36:28": [2, 26, 10, 34],
  "36:29": [26, 24, 32],
  "36:30": [22, 19, 29, 40],
  "36:31": [19, 1],
  "36:32": [27, 26, 1, 13],
  "36:33": [27, 9, 26, 24],
  "36:34": [1, 13],
  "36:35": [29, 15, 28, 37],
  "36:36": [0],
  "36:37": [15, 10, 37, 28],
  "36:38": [15, 1, 24],
  "36:39": [12, 17, 28],

  // 37. Difficulty of detecting
  "37:1": [27, 26, 28, 13],
  "37:2": [6, 13, 28, 1],
  "37:3": [16, 17, 26, 24],
  "37:4": [26],
  "37:5": [2, 13, 18, 17],
  "37:6": [2, 39, 30, 16],
  "37:7": [29, 1, 4, 16],
  "37:8": [2, 18, 26, 31],
  "37:9": [3, 4, 16, 35],
  "37:10": [30, 28, 40, 19],
  "37:11": [35, 36, 37, 32],
  "37:12": [27, 13, 1, 39],
  "37:13": [11, 22, 39, 30],
  "37:14": [27, 3, 15, 28],
  "37:15": [19, 29, 39, 25],
  "37:16": [25, 34, 6, 35],
  "37:17": [3, 27, 35, 16],
  "37:18": [2, 24, 26],
  "37:19": [35, 38],
  "37:20": [19, 35, 16],
  "37:21": [18, 1, 16, 10],
  "37:22": [35, 3, 15, 19],
  "37:23": [1, 18, 10, 24],
  "37:24": [35, 33, 27, 22],
  "37:25": [18, 28, 32, 9],
  "37:26": [3, 27, 29, 18],
  "37:27": [27, 40, 28, 8],
  "37:28": [26, 24, 32, 28],
  "37:29": [-1],
  "37:30": [22, 19, 29, 28],
  "37:31": [2, 21],
  "37:32": [5, 28, 11, 29],
  "37:33": [2, 5],
  "37:34": [12, 26],
  "37:35": [1, 15],
  "37:36": [15, 10, 37, 28],
  "37:37": [0],
  "37:38": [34, 21],
  "37:39": [35, 18],

  // 38. Extent of automation
  "38:1": [28, 26, 18, 35],
  "38:2": [28, 26, 35, 10],
  "38:3": [14, 13, 17, 28],
  "38:4": [23],
  "38:5": [17, 14, 13],
  "38:6": [-1],
  "38:7": [35, 13, 16],
  "38:8": [-1],
  "38:9": [28, 10],
  "38:10": [2, 35],
  "38:11": [13, 35],
  "38:12": [15, 32, 1, 13],
  "38:13": [18, 1],
  "38:14": [25, 13],
  "38:15": [6, 9],
  "38:16": [-1],
  "38:17": [26, 2, 19],
  "38:18": [8, 32, 19],
  "38:19": [2, 32, 13],
  "38:20": [-1],
  "38:21": [28, 2, 27],
  "38:22": [23, 28],
  "38:23": [35, 10, 18, 5],
  "38:24": [35, 33],
  "38:25": [24, 28, 35, 30],
  "38:26": [35, 13],
  "38:27": [11, 27, 32],
  "38:28": [28, 26, 10, 34],
  "38:29": [28, 26, 18, 23],
  "38:30": [2, 33],
  "38:31": [2],
  "38:32": [1, 26, 13],
  "38:33": [1, 12, 34, 3],
  "38:34": [1, 35, 13],
  "38:35": [27, 4, 1, 35],
  "38:36": [15, 24, 10],
  "38:37": [34, 27, 25],
  "38:38": [0],
  "38:39": [5, 12, 35, 26],

  // 39. Productivity
  "39:1": [35, 26, 24, 37],
  "39:2": [28, 27, 15, 3],
  "39:3": [18, 4, 28, 38],
  "39:4": [30, 7, 14, 26],
  "39:5": [10, 26, 34, 31],
  "39:6": [10, 35, 17, 7],
  "39:7": [2, 6, 34, 10],
  "39:8": [35, 37, 10, 2],
  "39:9": [-1],
  "39:10": [28, 15, 10, 36],
  "39:11": [10, 37, 14],
  "39:12": [14, 10, 34, 40],
  "39:13": [35, 3, 22, 39],
  "39:14": [29, 28, 10, 18],
  "39:15": [35, 10, 2, 18],
  "39:16": [20, 10, 16, 38],
  "39:17": [35, 21, 28, 10],
  "39:18": [26, 17, 19, 1],
  "39:19": [35, 10, 38, 19],
  "39:20": [1],
  "39:21": [35, 20, 10],
  "39:22": [28, 10, 29, 35],
  "39:23": [28, 10, 35, 23],
  "39:24": [13, 15, 23],
  "39:25": [-1],
  "39:26": [35, 38],
  "39:27": [1, 35, 10, 38],
  "39:28": [1, 10, 34, 28],
  "39:29": [18, 10, 32, 1],
  "39:30": [22, 35, 13, 24],
  "39:31": [35, 22, 18, 39],
  "39:32": [35, 28, 2, 24],
  "39:33": [1, 28, 7, 10],
  "39:34": [1, 32, 10, 25],
  "39:35": [1, 35, 28, 37],
  "39:36": [12, 17, 28, 24],
  "39:37": [35, 18, 27, 2],
  "39:38": [5, 12, 35, 26],
  "39:39": [0],

};

// === Lookup Helpers ===

// Build fast-access maps for parameter and principle lookups.
const _parameterById = new Map(TRIZ_PARAMETERS.map(p => [p.id, p]));
const _principleById = new Map(TRIZ_PRINCIPLES.map(p => [p.id, p]));

/**
 * Look up a TRIZ parameter by ID.
 * @param {number} id - Parameter ID (1–39)
 * @returns {{ id: number, name: string } | undefined}
 */
export function getParameterById(id) {
  return _parameterById.get(id);
}

/**
 * Look up a TRIZ principle by ID.
 * @param {number} id - Principle ID (1–40)
 * @returns {{ id: number, name: string, canonicalDescription: string[] } | undefined}
 */
export function getPrincipleById(id) {
  return _principleById.get(id);
}

/**
 * Deterministic contradiction-matrix lookup.
 *
 * Distinguishes:
 *   - "matrix_data_missing": key not in TRIZ_MATRIX (data not yet entered)
 *   - "ok" with []:           key present, value is [] (verified empty cell)
 *   - "ok" with [1,5,6]:      key present, principles found
 *
 * @param {number} improvingId - Improving parameter ID (1–39)
 * @param {number} worseningId - Worsening parameter ID (1–39)
 * @returns {{ status: "ok" | "matrix_data_missing", principles: number[] }}
 */
export function getPrinciplesForContradiction(improvingId, worseningId) {
  const key = `${improvingId}:${worseningId}`;
  if (!(key in TRIZ_MATRIX)) {
    return { status: "matrix_data_missing", principles: [] };
  }
  return { status: "ok", principles: TRIZ_MATRIX[key] };
}

/**
 * Compute the deduplicated, sorted candidate-principle union from contradiction mappings.
 *
 * @param {{ matrixPrinciples: number[] }[]} mappings - Array of per-contradiction mappings
 * @returns {number[]} Sorted array of unique principle IDs
 */
export function computeCandidateUnion(mappings) {
  const ids = new Set();
  for (const m of mappings) {
    for (const id of m.matrixPrinciples) {
      ids.add(id);
    }
  }
  return [...ids].sort((a, b) => a - b);
}

// === Reference Data Validation ===

/**
 * Validate TRIZ reference data completeness.
 *
 * Two levels:
 *   1. Global completeness: status of the entire reference data set.
 *   2. Case-specific readiness: whether a specific set of contradictions
 *      can be used for a research run (all required matrix cells entered,
 *      all required canonical descriptions provided).
 *
 * A Solution Generation run does NOT require the entire matrix or all 40
 * canonical descriptions to be complete. It only requires completeness for
 * the currently selected contradictions and their resulting candidate principles.
 *
 * @param {{ id: string, improvingParameterId: number, worseningParameterId: number }[] | null} contradictions
 *   If provided, validates case-specific readiness for these contradictions.
 *   If null, returns only global completeness.
 * @returns {object} Validation result
 */
export function validateReferenceData(contradictions = null) {
  const issues = [];

  // --- Global completeness ---
  const parametersReady = TRIZ_PARAMETERS.length === 39;
  if (!parametersReady) issues.push("Parameter list incomplete (expected 39)");

  const principleNamesReady = TRIZ_PRINCIPLES.length === 40;
  if (!principleNamesReady) issues.push("Principle list incomplete (expected 40)");

  const descriptionsProvided = TRIZ_PRINCIPLES.filter(
    p => Array.isArray(p.canonicalDescription) && p.canonicalDescription.length > 0
  ).length;
  const descriptionsComplete = descriptionsProvided === 40;

  const matrixCellsProvided = Object.keys(TRIZ_MATRIX).length;

  // Check for invalid principle IDs referenced by matrix cells
  for (const [key, ids] of Object.entries(TRIZ_MATRIX)) {
    if (!Array.isArray(ids)) {
      issues.push(`Matrix cell ${key} has non-array value`);
      continue;
    }
    for (const id of ids) {
      if (!Number.isInteger(id) || id < 1 || id > 40) {
        issues.push(`Matrix cell ${key} references invalid principle ID ${id}`);
      }
    }
    // Validate key format
    const parts = key.split(":");
    if (parts.length !== 2) {
      issues.push(`Matrix key "${key}" has invalid format (expected "improvingId:worseningId")`);
    } else {
      const impId = Number(parts[0]);
      const worId = Number(parts[1]);
      if (!_parameterById.has(impId)) issues.push(`Matrix key "${key}" references invalid improving parameter ID ${impId}`);
      if (!_parameterById.has(worId)) issues.push(`Matrix key "${key}" references invalid worsening parameter ID ${worId}`);
    }
  }

  // Check for duplicate parameter IDs
  const paramIds = new Set();
  for (const p of TRIZ_PARAMETERS) {
    if (paramIds.has(p.id)) issues.push(`Duplicate parameter ID ${p.id}`);
    paramIds.add(p.id);
  }

  // Check for duplicate principle IDs
  const princIds = new Set();
  for (const p of TRIZ_PRINCIPLES) {
    if (princIds.has(p.id)) issues.push(`Duplicate principle ID ${p.id}`);
    princIds.add(p.id);
  }

  const result = {
    global: {
      parametersReady,
      principleNamesReady,
      descriptionsComplete,
      descriptionsProvided,
      descriptionsTotal: TRIZ_PRINCIPLES.length,
      matrixCellsProvided,
      issues: [...issues]
    },
    case: null
  };

  // --- Case-specific readiness ---
  if (contradictions && contradictions.length > 0) {
    const caseIssues = [];
    const missingMatrixCells = [];
    const missingDescriptions = [];
    const allCandidateIds = new Set();

    for (const c of contradictions) {
      // Validate parameter IDs exist
      if (!_parameterById.has(c.improvingParameterId)) {
        caseIssues.push(`Contradiction ${c.id}: invalid improving parameter ID ${c.improvingParameterId}`);
      }
      if (!_parameterById.has(c.worseningParameterId)) {
        caseIssues.push(`Contradiction ${c.id}: invalid worsening parameter ID ${c.worseningParameterId}`);
      }

      const lookup = getPrinciplesForContradiction(c.improvingParameterId, c.worseningParameterId);
      if (lookup.status === "matrix_data_missing") {
        const cellKey = `${c.improvingParameterId}:${c.worseningParameterId}`;
        missingMatrixCells.push({ contradictionId: c.id, cellKey });
        caseIssues.push(
          `Contradiction ${c.id}: matrix cell ${cellKey} not yet entered`
        );
      } else {
        for (const id of lookup.principles) {
          allCandidateIds.add(id);
        }
      }
    }

    // Check canonical descriptions for candidate principles
    for (const id of [...allCandidateIds].sort((a, b) => a - b)) {
      const p = _principleById.get(id);
      if (!p) {
        caseIssues.push(`Candidate principle ${id} not found in reference data`);
        missingDescriptions.push({ id, name: "(unknown)" });
      } else if (
        !Array.isArray(p.canonicalDescription) ||
        p.canonicalDescription.length === 0
      ) {
        missingDescriptions.push({ id: p.id, name: p.name });
        caseIssues.push(
          `Candidate principle ${id} (${p.name}): canonical description not yet provided`
        );
      }
    }

    result.case = {
      researchReady: caseIssues.length === 0,
      missingMatrixCells,
      missingDescriptions,
      candidatePrincipleCount: allCandidateIds.size,
      issues: caseIssues
    };
  }

  return result;
}
